// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class FlowTargetEventKeys
    {
        public const string ROOT = "root";

        public static string[] GetSupportedKeys()
        {
            return PromptIntentContractRegistry.GetFlowTargetEventKeys();
        }

        public static bool IsSupported(string eventKey)
        {
            return PromptIntentContractRegistry.IsSupportedFlowTargetEventKey(eventKey);
        }
    }
}
