// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class GameplaySignalIds
    {

        private static readonly string[] All =
        {
        };

        public static string[] GetAll()
        {
            var copied = new string[All.Length];
            for (int i = 0; i < All.Length; i++)
                copied[i] = All[i];
            return copied;
        }
    }
}
