// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentObjectiveKinds
    {
        public const string UNLOCK_OBJECT = "unlock_object";
        public const string WAIT_SECONDS = "wait_seconds";

        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetObjectiveKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedObjectiveKind(kind);
        }

        public static bool CanAbsorbArrow(string kind)
        {
            return PromptIntentContractRegistry.ObjectiveCanAbsorbArrow(kind);
        }

        public static bool RequiresInputItem(string kind)
        {
            return PromptIntentContractRegistry.ObjectiveRequiresInputItem(kind);
        }
    }
}
