// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentConditionKinds
    {
        public const string START = "start";
        public const string STAGE_COMPLETED = "stage_completed";
        public const string BALANCE_AT_LEAST = "balance_at_least";
        public const string UNLOCK_COMPLETED = "unlock_completed";
        public const string CAPABILITY_LEVEL_AT_LEAST = "capability_level_at_least";

        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetConditionKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedConditionKind(kind);
        }
    }
}
