// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class SystemActionIds
    {
        public const string REVEAL_ENDCARD_UI = "reveal_endcard_ui";
        public const string END_GAME = "end_game";
        public const string FOCUS_CAMERA_ON_TARGET = "focus_camera_on_target";
        public const string SHOW_ARROW_ON_TARGET = "show_arrow_on_target";
        public const string HIDE_GUIDE = "hide_guide";
        public const string SET_CAPABILITY_LEVEL = "set_capability_level";
        public const string ENDCARD_UI_OBJECT_ID = "endcard_ui";
        public const string RUNTIME_TARGET_SEPARATOR = "::";

        public static bool IsSupportedAuthoring(string id)
        {
            return PromptIntentCapabilityRegistry.IsSupportedSystemActionAuthoringId(id);
        }

        public static bool RequiresTargetObjectId(string id)
        {
            return PromptIntentCapabilityRegistry.SystemActionRequiresTargetObjectId(id);
        }

        public static bool IsSupportedEventKey(string eventKey)
        {
            return FlowTargetEventKeys.IsSupported(eventKey);
        }

        public static string BuildRuntimeTargetId(string authoringId, string targetId)
        {
            return BuildRuntimeTargetId(
                authoringId,
                targetId,
                PromptIntentCapabilityRegistry.GetSystemActionDefaultEventKey(authoringId));
        }

        public static string BuildRuntimeTargetId(string authoringId, string targetId, string eventKey)
        {
            string normalizedAuthoringId = Normalize(authoringId);
            if (!IsSupportedAuthoring(normalizedAuthoringId))
                return string.Empty;

            if (!RequiresTargetObjectId(normalizedAuthoringId))
                return normalizedAuthoringId;

            string normalizedTargetId = Normalize(targetId);
            string normalizedEventKey = Normalize(eventKey);
            if (string.IsNullOrEmpty(normalizedTargetId) || !IsSupportedEventKey(normalizedEventKey))
                return string.Empty;

            return normalizedAuthoringId +
                RUNTIME_TARGET_SEPARATOR + normalizedTargetId +
                RUNTIME_TARGET_SEPARATOR + normalizedEventKey;
        }

        public static bool IsSupportedRuntimeTargetId(string id)
        {
            return TryParseRuntimeTargetId(id, out _, out _, out _);
        }

        public static bool TryParseRuntimeTargetId(string id, out string authoringId, out string targetId, out string eventKey)
        {
            authoringId = string.Empty;
            targetId = string.Empty;
            eventKey = string.Empty;

            string normalized = Normalize(id);
            if (string.IsNullOrEmpty(normalized))
                return false;

            string[] tokens = normalized.Split(
                new[] { RUNTIME_TARGET_SEPARATOR },
                System.StringSplitOptions.None);

            if (tokens.Length == 1)
            {
                if (!IsSupportedAuthoring(normalized) || RequiresTargetObjectId(normalized))
                    return false;

                authoringId = normalized;
                return true;
            }

            if (tokens.Length != 3)
                return false;

            string parsedAuthoringId = Normalize(tokens[0]);
            string parsedTargetId = Normalize(tokens[1]);
            string parsedEventKey = Normalize(tokens[2]);
            if (!IsSupportedAuthoring(parsedAuthoringId) ||
                !RequiresTargetObjectId(parsedAuthoringId) ||
                string.IsNullOrEmpty(parsedTargetId) ||
                !IsSupportedEventKey(parsedEventKey))
                return false;

            authoringId = parsedAuthoringId;
            targetId = parsedTargetId;
            eventKey = parsedEventKey;
            return true;
        }

        private static string Normalize(string id)
        {
            return string.IsNullOrWhiteSpace(id) ? string.Empty : id.Trim();
        }
    }
}
