// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class CurrencyStartVisualRules
    {
        public const string STACKED = "stacked";
        public const string NONE = "none";

        public static string[] GetSupportedModes()
        {
            return PromptIntentContractRegistry.GetCurrencyStartVisualModes();
        }

        public static string Validate(string startVisualMode, string label)
        {
            if (string.IsNullOrWhiteSpace(startVisualMode))
                return label + " is required.";

            string normalized = startVisualMode.Trim();
            if (PromptIntentContractRegistry.IsSupportedCurrencyStartVisualMode(normalized))
                return null;

            string[] supportedModes = PromptIntentContractRegistry.GetCurrencyStartVisualModes();
            if (supportedModes.Length == 0)
                return label + " has no supported modes.";
            if (supportedModes.Length == 1)
                return label + " must be '" + supportedModes[0] + "'.";

            string supportedList = supportedModes[0];
            for (int i = 1; i < supportedModes.Length - 1; i++)
                supportedList += "', '" + supportedModes[i];

            supportedList += "' or '" + supportedModes[supportedModes.Length - 1];
            return label + " must be '" + supportedList + "'.";
        }

        public static bool ShouldCreateInitialStack(string startVisualMode)
        {
            return string.Equals(startVisualMode != null ? startVisualMode.Trim() : string.Empty, STACKED, System.StringComparison.Ordinal);
        }
    }
}
