// Generated by sync-contract-registry from agent_prompt_generator_unity/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class CurrencyStartVisualRules
    {
        public const string STACKED = "stacked";
        public const string NONE = "none";

        public static string[] GetSupportedModes()
        {
            return PromptIntentContractRegistry.GetCurrencyStartVisualModes();
        }

        public static string Validate(string startVisualMode, string label)
        {
            if (string.IsNullOrWhiteSpace(startVisualMode))
                return label + "가 필요합니다.";

            string normalized = startVisualMode.Trim();
            if (PromptIntentContractRegistry.IsSupportedCurrencyStartVisualMode(normalized))
                return null;

            string[] supportedModes = PromptIntentContractRegistry.GetCurrencyStartVisualModes();
            if (supportedModes.Length == 0)
                return label + "는 지원되는 mode가 없습니다.";
            if (supportedModes.Length == 1)
                return label + "는 '" + supportedModes[0] + "'이어야 합니다.";

            string supportedList = supportedModes[0];
            for (int i = 1; i < supportedModes.Length - 1; i++)
                supportedList += "', '" + supportedModes[i];

            supportedList += "' 또는 '" + supportedModes[supportedModes.Length - 1];
            return label + "는 '" + supportedList + "'이어야 합니다.";
        }

        public static bool ShouldCreateInitialStack(string startVisualMode)
        {
            return string.Equals(startVisualMode != null ? startVisualMode.Trim() : string.Empty, STACKED, System.StringComparison.Ordinal);
        }
    }
}
