// Generated by sync-contract-registry from agent_prompt_generator_unity/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class FlowTargetEventKeys
    {
        public const string ROOT = "Root";
        public const string GET_ITEM = "GetItem";
        public const string DROP_ITEM = "DropItem";
        public const string SELL_ITEM = "SellItem";
        public const string COLLECT_MONEY = "CollectMoney";

        public static string[] GetSupportedKeys()
        {
            return PromptIntentContractRegistry.GetFlowTargetEventKeys();
        }

        public static bool IsSupported(string eventKey)
        {
            return PromptIntentContractRegistry.IsSupportedFlowTargetEventKey(eventKey);
        }
    }
}
