// Generated by sync-contract-registry from agent_prompt_generator_unity/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentEffectKinds
    {
        public const string REVEAL_OBJECT = "reveal_object";
        public const string ACTIVATE_OBJECT = "activate_object";
        public const string FOCUS_CAMERA = "focus_camera";
        public const string SHOW_ARROW = "show_arrow";
        public const string SPAWN_CUSTOMER = "spawn_customer";
        public const string REVEAL_ENDCARD = "reveal_endcard";
        public const string HIDE_GUIDE = "hide_guide";
        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetEffectKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedEffectKind(kind);
        }

        public static bool RequiresTargetObjectId(string kind)
        {
            return PromptIntentContractRegistry.EffectRequiresTargetObjectId(kind);
        }

        public static bool IsNonBlockingSystemAction(string kind)
        {
            return PromptIntentContractRegistry.EffectIsNonBlockingSystemAction(kind);
        }

        public static bool SupportsExplicitTiming(string kind)
        {
            return PromptIntentContractRegistry.EffectSupportsExplicitTiming(kind);
        }

        public static bool RequiresEventKey(string kind)
        {
            return PromptIntentContractRegistry.EffectRequiresEventKey(kind);
        }

        public static bool SupportsEventKey(string kind)
        {
            return PromptIntentContractRegistry.EffectSupportsEventKey(kind);
        }
    }

    public static class PromptIntentEffectTimingKinds
    {
        public const string ARRIVAL = "arrival";
        public const string COMPLETED = "completed";

        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetEffectTimingKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedEffectTimingKind(kind);
        }
    }
}
