// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentConditionKinds
    {
        public const string START = "start";
        public const string STAGE_COMPLETED = "stage_completed";
        public const string BALANCE_AT_LEAST = "balance_at_least";
        public const string UNLOCK_COMPLETED = "unlock_completed";
        public const string ITEM_GENERATED = "item_generated";
        public const string ITEM_COLLECTED = "item_collected";
        public const string ITEM_CONVERTED = "item_converted";
        public const string RAIL_ITEM_ARRIVED = "rail_item_arrived";
        public const string SALE_COMPLETED = "sale_completed";
        public const string MONEY_COLLECTED = "money_collected";
        public const string CUSTOMER_SERVED = "customer_served";

        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetConditionKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedConditionKind(kind);
        }
    }
}
