// Generated by sync-contract-registry from ai_playable_server/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentObjectRoles
    {
        public const string PLAYER = "player";
        public const string UNLOCK_PAD = "unlock_pad";

        public static string[] GetSupportedRoles()
        {
            return PromptIntentContractRegistry.GetObjectRoleValues();
        }

        public static bool IsSupported(string role)
        {
            return PromptIntentContractRegistry.IsSupportedObjectRole(role);
        }

        public static bool IsCatalogBacked(string role)
        {
            return PromptIntentContractRegistry.IsCatalogBackedObjectRole(role);
        }

        public static bool SupportsDesignId(string role)
        {
            return PromptIntentContractRegistry.ObjectRoleSupportsDesignId(role);
        }

        public static bool SupportsFeatureOptions(string role)
        {
            return PromptIntentContractRegistry.ObjectRoleSupportsFeatureOptions(role);
        }

    }
}
