// Generated by sync-contract-registry from agent_prompt_generator_unity/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentObjectiveKinds
    {
        public const string UNLOCK_OBJECT = "unlock_object";
        public const string COLLECT_ITEM = "collect_item";
        public const string CONVERT_ITEM = "convert_item";
        public const string SELL_ITEM = "sell_item";
        public const string COLLECT_CURRENCY = "collect_currency";
        public const string WAIT_SECONDS = "wait_seconds";

        public static string[] GetSupportedKinds()
        {
            return PromptIntentContractRegistry.GetObjectiveKindValues();
        }

        public static bool IsSupported(string kind)
        {
            return PromptIntentContractRegistry.IsSupportedObjectiveKind(kind);
        }

        public static bool CanAbsorbArrow(string kind)
        {
            return PromptIntentContractRegistry.ObjectiveCanAbsorbArrow(kind);
        }

        public static bool RequiresInputItem(string kind)
        {
            return PromptIntentContractRegistry.ObjectiveRequiresInputItem(kind);
        }
    }
}
