// Generated by sync-contract-registry from agent_prompt_generator_unity/contracts/PLAYABLE_PROMPT_INTENT_REGISTRY.source.json.
// Do not edit manually.
namespace Supercent.PlayableAI.Common.Contracts
{
    public static class PromptIntentObjectRoles
    {
        public const string PLAYER = "player";
        public const string GENERATOR = "generator";
        public const string PROCESSOR = "processor";
        public const string SELLER = "seller";
        public const string UNLOCK_PAD = "unlock_pad";
        public const string PHYSICS_AREA = "physics_area";
        public const string RAIL = "rail";

        public static string[] GetSupportedRoles()
        {
            return PromptIntentContractRegistry.GetObjectRoleValues();
        }

        public static bool IsSupported(string role)
        {
            return PromptIntentContractRegistry.IsSupportedObjectRole(role);
        }

        public static bool IsCatalogBacked(string role)
        {
            return PromptIntentContractRegistry.IsCatalogBackedObjectRole(role);
        }

        public static bool SupportsDesignId(string role)
        {
            return PromptIntentContractRegistry.ObjectRoleSupportsDesignId(role);
        }

        public static bool SupportsScenarioOptions(string role)
        {
            return PromptIntentContractRegistry.ObjectRoleSupportsScenarioOptions(role);
        }

        public static bool IsRailSinkTargetRoleSupported(string role)
        {
            return PromptIntentContractRegistry.ObjectRoleSupportsRailSinkTarget(role);
        }
    }
}
